name: Auto Label

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  label:
    name: Auto Label PR
    uses: groupsmix/shared-workflows/.github/workflows/label.yml@main
    with:
      use-default-config: true
