name: Stale

on:
  schedule:
    - cron: "0 0 * * *"

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    name: Close Stale Issues & PRs
    uses: groupsmix/shared-workflows/.github/workflows/stale.yml@main
    with:
      days-before-stale: 60
      days-before-close: 14
      exempt-issue-labels: "pinned,security,bug"
